# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20160314_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcontent',
            name='md5',
            field=models.CharField(blank=True, default=b'', max_length=32),
        ),
    ]
