# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160318_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('md5', models.CharField(blank=True, default=b'', max_length=32)),
                ('modified', models.DateTimeField(blank=True)),
            ],
        ),
    ]
